server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.6.128
    username: leyou
    password: leyou
    virtual-host: leyou
  redis:
    host: 192.168.6.128


ly:
  sms:
    accessKeyId: LTAIf5vJTEe7oiPa
    accessKeySecret: A2ZGBWfrkz9arF908cmDWXmIrAlngA
    signName: 乐友商城
    verifyCodeTemplate: SMS_133976814